apiVersion: v1
kind: Service
metadata:
  name: healthcheckerclientcsharp
  labels:
    app: healthcheckerclientcsharp
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: {{ .Values.healthcheckerclientcsharp.service.grpc.externalPort }}
    name: grpc
    protocol: TCP
    targetPort: {{ .Values.healthcheckerclientcsharp.service.grpc.internalPort }}
  selector:
    app: healthcheckerclientcsharp
  type: ClusterIP