apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheckerclientpy
  labels:
    app: healthcheckerclientpy
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheckerclientpy
  template:
    metadata:
      labels:
        app: healthcheckerclientpy
    spec:
      enableServiceLinks: false
      containers:
      - name: healthcheckerclientpy
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.healthcheckerclientpy.service.grpc.internalPort }}
        args:
          - {{ .Values.target_address }}