apiVersion: v1
kind: Service
metadata:
  name: healthcheckerclientpy
  labels:
    app: healthcheckerclientpy
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: {{ .Values.healthcheckerclientpy.service.grpc.externalPort }}
    name: grpc
    protocol: TCP
    targetPort: {{ .Values.healthcheckerclientpy.service.grpc.internalPort }}
  selector:
    app: healthcheckerclientpy
  type: ClusterIP