apiVersion: v1
kind: Service
metadata:
  name: healthcheckerclientpy
  labels:
    app: healthcheckerclientpy
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: healthcheckerclientpy
  type: ClusterIP