apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheckerclientcsharp
  labels:
    app: healthcheckerclientcsharp
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheckerclientcsharp
  template:
    metadata:
      labels:
        app: healthcheckerclientcsharp
    spec:
      enableServiceLinks: false
      containers:
      - name: healthcheckerclientcsharp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.healthcheckerclientcsharp.service.grpc.internalPort }}